add command and query for get review scorecards
topcoder-platform/tc-database-scripts pull request #5
Opened 2016-11-16 01:03 UTC by skyhit

2016-11-21 17:11 UTC, ajefts requested changes

2016-11-21 17:11 UTC, ajefts commented on tcs_catalog/query_tool/query_get_review_scorecard.txt
> +select * from scorecard where scorecard_type_id = 2
@skyhit I think this is wrong.  We should be pulling the active scorecards only for the current challenge type, so we'll need to pass in a param for the challenge type...

2016-11-22 07:59 UTC, skyhit commented on tcs_catalog/query_tool/query_get_review_scorecard.txt
> +select * from scorecard where scorecard_type_id = 2
@ajefts ok, so let work on a quick fix?

2016-11-22 14:11 UTC, ajefts commented on tcs_catalog/query_tool/query_get_review_scorecard.txt
> +select * from scorecard where scorecard_type_id = 2
@skyhit Yes, please let's get that done and then I'll merge and test.  Thanks.

2016-12-12 16:01 UTC, merged